### ISSUE TITLE
Add tracking to Whatsapp button

### ISSUE THREAD

**Issue by giselle724** [logicwisesoftware/zcova#302]
Add tracking to Whatsapp button.

**Comment by logicwisesoftware** [comment]
Seems like the whatsapp google tag tracker had already added 7 days ago.

<img width="713" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/efa727c0-7453-46d5-b9a0-8887f4c6b62a">

**Comment by giselle724** [comment]
Hi, apology. Could you add tracking in meta please?

**Comment by logicwisesoftware** [comment]
Hi,

The FB meta tracker is also there according to the google tag.

<img width="811" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/fc1e8a87-ad9d-4c24-9b4b-3149b9644352">


Would you be able to check with the person who handles all the tracker tags? Accoding to the log, it's done by these emails. Probably best to ask them since they are maintaining the tags.

<img width="340" alt="image" src="https://github.com/logicwisesoftware/zcova/assets/106665593/478123d9-7a46-40df-a241-21f66ba34032">
