### ISSUE TITLE
March Promo Page Issue

### ISSUE THREAD

**Issue by Shellytsy** [logicwisesoftware/zcova#354]
Hi team, our Google ads agency faced issue with the landing page, please refer the below and assist as soon as possible, thank you.

From our agency:
But we found that URL destination "https://zcova.com/marchpromo24" is not working even after we appeal. Google mention it has been disapproved because it cannot be crawl by the AdsBot.

Will need web developer help to check on the website coding and ensure that it does not return an HTTP error to Goolge AdsBot when crawled.

Here's a link that the web developer can go through https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers?visit_id=638253738906696533-3152135902&rd=1

**Comment by logicwisesoftware** [comment]
We just made some changes for the crawler to access. You may ask the agency to give it another try.

**Comment by Shellytsy** [comment]
Hi team, the link is still not working for the ads.

This is from our agency:
Further investigation, I found a link ("https://zcova.com/international/marchpromo24") inside the actual URL that's leading to 404 error. This could be the reason Google reject the ads. Will need the web developer to look into this and make changes.

Please help rectify, thank you

**Comment by logicwisesoftware** [comment]
This link is not correct https://zcova.com/international/marchpromo24. It should be https://zcova.com/marchpromo24

Previously if the AdsBot access https://zcova.com/marchpromo24 it will redirect to https://zcova.com/international/marchpromo24 because of the their IP is located outside of Malaysia.

We have make some changes yesterday not to redirect if it is AdsBot.
